version: '2.1'
services:
  sinusbot:
    image: galexrt/sinusbot
    environment:
      - PGID=3000
      - PUID=3000
    ports:
      - "8087:8087"
    restart: always
    volumes:
      - /storage/sinusbot/scripts:/sinusbot/scripts
      - /storage/sinusbot/data:/sinusbot/data  
  transmission:
    image: linuxserver/transmission
    environment: 
      - PGID=1002
      - PUID=1002
    restart: always
    volumes:
      - /storage/transmission/config:/config
      - /storage/media:/downloads
      - /storage/transmission/watch:/watch
    ports:
      - "15000:9091"
      - "51413:51413"
      - "51413:51413/udp"
  ts3server:
    image: teamspeak
    restart: always
    environment:
      - PGID=1003
      - PUID=1003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/teamspeak:/var/ts3server/
    environment:
      TS3SERVER_LICENSE: accept
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
  nzbget:
    image: linuxserver/nzbget
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/nzbget:/config
      - /storage/media:/downloads
    ports:
      - "6789:6789"
  sonarr:
    image: linuxserver/sonarr
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/sonarr:/config
      - /storage/media:/downloads
      - /storage/media/Series:/tv
      - /storage/media/Anime:/anime
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/radarr:/config
      - /storage/media:/downloads
      - /storage/media/Movies:/movies
      - /archive/media/Movies:/archived-movies
    ports:
      - 7878:7878
  plexrequests:
    image: linuxserver/plexrequests
    restart: always
    environment:
      - PGID=3000
      - PUID=3000
      - URL_BASE=/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/plexrequests:/config
    ports:
      - "8030:3000"
  tautulli:
    image: linuxserver/tautulli
    restart: always
    environment:
      - PGID=65534
      - PUID=112
    volumes:
      - /storage/plexpy:/config
      - /storage/plexpy/logs:/logs:ro
    ports:
      - "8181:8181"
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /storage/nginx/config:/etc/nginx/conf.d
      - /storage/nginx/dhparam:/dhparam
      - /etc/letsencrypt:/certs
  nextclouddb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /storage/nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - nextcloud.env
  nextcloud:  
    image: nextcloud:apache
    restart: always
    volumes:
      - /storage/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextclouddb
    env_file:
      - nextcloud.env
    depends_on:
      - nextclouddb
