version: '2'
services:
  transmission:
    image: linuxserver/transmission
    environment: 
      - PGID=1002
      - PUID=1002
    restart: always
    volumes:
      - /storage/transmission/config:/config
      - /storage/media:/downloads
      - /storage/transmission/watch:/watch
    ports:
      - "15000:9091"
      - "51413:51413"
      - "51413:51413/udp"
  ts3server:
    image: linuxserver/gsm-ts3
    restart: always
    environment:
      - PGID=1003
      - PUID=1003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/teamspeak:/config
    network_mode: "host"
  nzbget:
    image: linuxserver/nzbget
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/nzbget:/config
      - /storage/media:/downloads
    ports:
      - "6789:6789"
  sonarr:
    image: linuxserver/sonarr
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/sonarr:/config
      - /storage/media:/downloads
      - /storage/media/Series:/tv
      - /storage/media/Anime:/anime
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    restart: always
    environment:
      - PGID=1002
      - PUID=1002
    volumes:
      - /storage/radarr:/config
      - /storage/media:/downloads
      - /storage/media/Movies:/movies
    ports:
      - 7878:7878
  plexrequests:
    image: linuxserver/plexrequests
    restart: always
    environment:
      - PGID=3000
      - PUID=3000
      - URL_BASE=/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/plexrequests:/config
    ports:
      - "8030:3000"
  plexpy:
    image: linuxserver/plexpy    
    restart: always
    environment:
      - PGID=65534
      - PUID=112
    volumes:
      - /storage/plexpy:/config
      - /storage/plexpy/logs:/logs:ro
    ports:
      - "8181:8181"

